spring:
  datasource:
    url: jdbc:mysql://localhost:3306/securityandoauth?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
server:
  port: 8082
security:
  basic:
    enabled: false
  user:
    name: admin
    password: 123456


